### ISSUE TITLE
Didn't work for me (SOLVED)

### ISSUE THREAD

**Issue by styopin** [danqing/Pinch#1]
Not working on macOS Ventura 13.1 with plugged monitor. 
Open at moment: Adobe InDesign, Safari, VSC, Mail App

**Comment by danqing** [comment]
Hey! Thank you for the report. When you click on the fix button, does your screen flicker for a second? (It should as the dock process is killed.)

And do you mind running `killall Dock` in your terminal to see if the command works for you?

**Comment by danqing** [comment]
@styopin I added another way to fix the problem with 1.1 — get it here and lmk if that works for you!

https://github.com/danqing/Pinch/releases/download/1.1/Pinch.zip

**Comment by styopin** [comment]
Unfortunately 1.1 still not work for me.
`Killall Dock` can't help too. 

It's so strange. Maybe the reason on the Adobe side?

**Comment by danqing** [comment]
Even if Adobe is messing up with the trackpad, the problem should be fixable on the system side I believe. Can you confirm that with 1.1, _right_ after you click Fix Pinch Gesture, the gesture stops working for 0.5s? (This version works by turning the gesture off and on again, which is reported on Twitter as a reliable way to fix the issue.)

**Comment by styopin** [comment]
Well, I have really different algorithm of actions before this happens.
For example, right now I catch this problem, but "Fix Pinch Gesture" can't help me. Display blinking once time only. Ok.
But when I run Preview (native Mac app), try pitching (didn't help), and after that run "Fix Pinch Gesture" again — it's works!

It is blow my mind! :)

**Comment by danqing** [comment]
Oh wow that's weird! Do you have a reliable way to make pinch fail? I have Adobe apps too so if you know how to trigger the issue I can see if I can do anything!

**Comment by bucweat** [comment]
Hi, 

Using Pinch 1.1 on MBP 2018 (Intel) with Ventura 13.1 and a connected screen. After installing Pinch it took a while for issue to pop up again, but it finally happened today (noticed in Safari), and Pinch did not solve the issue. The dock flashed, but pinch to zoom did not start working again. About a minute later after clicking through a couple of open apps trying pinch to zoom, it started working again. All other trackpad features still work when pinch to zoom stops...its just that feature that stops.

I did try running Pinch while pinch to zoom was working to see if feature stops while the app cycles the option, but I could not tell that it was turned off as pinch to zoom worked throughout the flashing caused by `killall Dock`. 

I have not found any way to make pinch to zoom fail...I mostly use it in Safari and Preview, but have apps like Parallels, Apple mail, messages, discord, Microsoft Teams and Signal running. Issue seems to just randomly show up and go away. I've not found anything in Unified Logs that might indicate what is going on...

Also running Pinch multiple times when pinch to zoom is broken does not seem to help. It just comes back after some period of time that is not associated with running Pinch. 

PS thank you for making app and trying to find solution...it is much appreciated. Happy to debug and try anything else you might find. If I come across any other possible solutions or indications will share them here :-)

PPS WRT Adobe I only have Acrobat Reader that I almost never use. So I doubt it is Adobe apps. I was thinking it might be terminal or Parallels...apps that "steal" the cursor...but so far not found anything definitive...

**Comment by styopin** [comment]
Bucweat, hi! 

You described my situation.
Exactly the same!

**Comment by danqing** [comment]
I'm still unable to reproduce this...

Maybe you can help me by trying the version below? This version disables pinch gesture for 5 seconds before re-enabling it. Can you check if:

1. After clicking on Fix Gesture you can't pinch in the next 5 seconds, and
2. Whether this fixes anything?

(The 1.1.1 build disables the gesture for just 0.5s before re-enabling, which works for me.)

[Pinch.zip](https://github.com/danqing/Pinch/files/10463166/Pinch.zip)

**Comment by bucweat** [comment]
Thanks :-) 

Downloaded the 5 second version provided here and it DOES disable the pinch to zoom for a  couple of seconds. So it could be the 1.1.1 version is not long enough to notice especially with the killall Dock happening.

 Keeping the 5 second version installed...just need to wait until pinch to zoom fails again...

**Comment by SuatBabatan** [comment]
this also worked for me too

**Comment by lblive** [comment]
I take the opportunity to share my experience. Until now, I always solved this problem by disabling and re-enabling pinch gesture in System Settings. And, I have noticed that in my case this solution only works if I wait a few seconds before re-enabling the gesture. (I use Stage Manager on macOS 13.1, MacBook Air M2, and this problem occurs even when using only Apple apps)

And Pinch version 1 doesn't solve the pinch problem, but it does allow me to solve another bug! From time to time, I can't swipe with two fingers to hide a notification or delete an email for example. Pinch 1 solves the bug every time. So thanks a lot!
(I haven’t tried the other versions yet)

**Comment by lblive** [comment]
I'm lucky today, I've already been able to test version 1.1.1 and version 5s in real condition 😅 I confirm that in my case version 1.1.1 does not work, but the 5 second version seems to work well.

Thanks a lot

**Comment by danqing** [comment]
Thank you for the info @lblive! So it looks like the 0.5s delay in 1.1.1 may be too quick for some systems.

I increased it to 1s here: https://github.com/danqing/Pinch/releases/download/1.2/Pinch.zip. If you may, want to help try this version out? I'm glad that the 5s version works, but it's a bit long haha.

**Comment by styopin** [comment]
@danqing, 1.1.1 and 1.2 is works for me! 

THANK YOU SO MUCH!

**Comment by bucweat** [comment]
Pinch to zoom finally stopped for me, but not in a way I expected. Pinch to zoom stopped working in Preview and Typora, but NOT in Safari. I'm not sure I've seen that before, but I flipped between those apps multiple times and it remained consistent. I then ran the 5 sec version of Pinch, and it didn't fix the problem right away (as in after flashing dock and counting 5 potatoes). Pinch to zoom DID start working again in Preview and Typora maybe 15 to 20 seconds after that. So there might be a time delay involved in the fix? 

Anyway, that is my experience so far...but I only have one data point to go on and one data point does not a trend make. 

As to closing this issue, yeah I know I've kind of hijacked things, but @danqing you might want to leave this open so that others can more easily find it as it contains some good troubleshooting tips and sets expectations...or maybe copy some of that to the README.md...my $0.02 :-)

**Comment by danqing** [comment]
> Pinch to zoom stopped working in Preview and Typora, but NOT in Safari.

That's interesting — if the gesture isn't failing system-wide, there may be some other issues involved. I don't think I've ever encountered that myself...

And yea thank you for the suggestion @bucweat — I'm gonna add a link to this issue from README.

**Comment by bucweat** [comment]
Adding another interesting experience I had today with pinch to zoom issue. BTW I updated to 13.2 over the weekend and still seeing pinch to zoom issue so it has not been fixed with system update.

Anyway, todays experience: I have two Safari windows open, pinch to zoom works in all the tabs of one window, but none of the tabs of the other. Doesn't matter which monitor the window is in (MBP with one external monitor).  If I drag tab from working window to not working window, pinch to zoom for that tab stops working. Drag the tab back to the working window and it starts working again. So it would seem that pinch to zoom is per window at least with Safari. I also had Preview open with pdf file and pinch to zoom did not work. It also did not work in any new pdf files I opened.

Ran Pinch a couple of times and at least initially pinch to zoom is not fixed for windows where it is not working, but continues to work in the one Safari window where it was working previously. A couple of minutes after running Pinch, pinch to zoom does start to work again in all windows.

**Comment by danqing** [comment]
Yea very interesting... I've never encountered "partial failure" — every time it broke for me it broke everything.

Are you running the 1 second version or the 5 second version @bucweat? Next time you encounter the issue, can you try toggling the pinch gesture off / on in system settings to see if that fixes things?

**Comment by Wieroo** [comment]
Macbook air m1 2020. Вентура 13.2.1
Проблема: 2 жеста лагают. А именно "Прокрутка двумя пальцами влево или вправо" при использовании сайтов для серфинга, когда я пытаюсь вернуться на страницу назад. Жест просто замирает и не дает смахнуть страницу назад или вперед. Такой баг уже где-то с лета 2022 года. Раньше он был примерно несколько раз в день, теперь несколько раз в неделю.
Недавно так же появился лаг уменьшения и увеличения масштаба двумя пальцами, что как раз описывают здесь. В целом команда "убить док" помогла. Я так же писал обращения в тех поддержку Apple^ но инженеры так и не дали ответ^ я кидал им видео и полные логи. Переустановка системы мне так же не помогла. Значит баг внутри самой системы, даже если ее обновлять.

**Comment by styopin** [comment]
@Wieroo, у меня такая же история с Сафари. Я все форумы эпловские перечитал по этой теме. И на это жалуются все, блин. И не первый год. И никто ничего не может решить. У меня цензурных слов нет ))) Я уверен, что страничный свайп двумя пальцами в Сафари и не работающий пинч-ту-зум — вещи точно взаимосвязанные. Отказывают обе и ровно в один момент. 

Откатывался на Каталину даже — там такой хрени не наблюдается. Сломали на Биг-суре, видимо.

**Comment by Wieroo** [comment]
> @Wierooу меня такая же история с сафари. Я перечитал все форумы Эпловских по этой теме. И все жалуются на это, блин. И не первый год. И никто не может решить ничего. У меня нет к цензурных слов ))) Я уверен, что страничный вайп двумя пальцами в сафари и не работающий пяпяп-ту-зум - вещи точно взаимосвязаны. Отказывают обе и ровно в один момент.
> 
> Я даже ехал на Каталия - там нет такой хрени. Вероятно, сломался на Биг-Суре.

Но у меня так же эти жесты лагают и в Хроме, после того как ломаются в Сафари. Да я сижу на Сафари больше, но проблема эта в целом в системе. Короче очень то грустно, что починить не могут( А еще была очень странная фишка. Когда баг проявлялся, я хотел его заснять на айфон, и как только я включал запись видео на айфоне, проблема сразу же пропадала и так много раз подряд. Как это связанно- я не знаю(

**Comment by Wieroo** [comment]
Единственное, что меня обнадеживает, что это проблема не только у меня, а она именно в системе. Надеюсь ее починят) Странно такие видеть в макосе

**Comment by krik215** [comment]
Holy, feels like a noob, but I've downloaded the zip, put it in apps, nothing has changed, even set up the folder in apps as a start up option, still can't get the icon on the top. Would u be so nice to explain why I can't even run the code

**Comment by siar26** [comment]
Hey,
I have tried to add a shortcut to Fix Pinch Gesture, it doesnt work why?

![CleanShot 2024-04-05 at 15 43 35@2x](https://github.com/danqing/Pinch/assets/44984411/76fc414c-46ce-45bf-97c0-2437b472cfa0)

**Comment by vernikr** [comment]
I suggest suing Apple since support is not responding.

The app doesn't help unfortunately. Of course tried a billion of other methods. Catalina worked well.
